### ISSUE TITLE
"Cannot find module .." error when running `ember g --help`

### ISSUE THREAD

**Issue by jflewis** [arschmitz/ember-cli-standard#4]
following stack trace occurs when running `ember help generate` or `ember g --help`

```
Cannot find module '../../lib/utilities/extend-from-application-entity'
Error: Cannot find module '../../lib/utilities/extend-from-application-entity'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/JLewis/prj/work/tls-client/node_modules/ember-cli-standard/blueprints/adapter/index.js:3:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by arschmitz** [comment]
fixed
